SDGSDB/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SDGSDB.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project
        public ActionResult InitiateProject()
        {
            return View();
        }
        public ActionResult AddMembersToTeam()
        {
            return View();
        }
        public ActionResult AddTeams()
        {
            return View();
        }
    }
}

SDGSDB/Views/Project/AddMembersToTeam.cshtml
@model SDGSDB.Models.TeamMembers
@{
    ViewBag.Title = "AddMembersToTeam";
    Layout = "~/Views/Layouts/_DashboardLayout.cshtml";
}

@Scripts.Render("~/Scripts/jquery-3.4.1.js")
@Scripts.Render("~/Scripts/jquery-3.4.1.min.js")
@Scripts.Render("~/Scripts/bootstrap.min.js")
<section class="content">


    <div class="row">

        <div class="col-md-12">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <div class="row">
                    @using (Html.BeginForm("AddMembersToTeam", "Project", FormMethod.Post, new { @class = "form", role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <fieldset>
                            <!-- Default box -->
                            <div class="box box-danger">
                                <div class="box-header with-border">
                                    <div class="well">
                                        <h3><img width="70" src="~/Images/sdgs_circle.png" /> Assign Members To A team</h3>
                                    </div>

                                </div>
                                <div class="box-body">
                                    <legend>Select Team Members</legend>
                                    @*@Html.ValidationSummary(true, null, new { @Class = "text-danger" })*@
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="form-group">

                                                @Html.LabelFor(m => m.Team_Id, htmlAttributes: new { @class = "control-label" })


                                                @Html.DropDownListFor(m => m.Team_Id, new List<SelectListItem> { new SelectListItem { Text = "Select Project", Value = " " }, new SelectListItem { Text = "Team 1", Value = "1" }, new SelectListItem { Text = "Team 2", Value = "2" }, new SelectListItem { Text = "Team 3", Value = "3" } }, htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.Team_Id, "", new { @class = "text-danger" })

                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <button type="submit" style="margin-top: 25px;" id="BtnRegistrationSubmit" class="btn btn-dropbox text-center"><i class="fa fa-search"> Search Members</i></button>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">

                                                @Html.LabelFor(m => m.EmployeeId, htmlAttributes: new { @class = "control-label" })


                                                @Html.DropDownListFor(m => m.EmployeeId, new List<SelectListItem> { new SelectListItem { Text = "Select Employee", Value = " " }, new SelectListItem { Text = "Emp 1", Value = "1" }, new SelectListItem { Text = "Emp 2", Value = "2" }, new SelectListItem { Text = "Emp 3", Value = "3" } }, htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.EmployeeId, "", new { @class = "text-danger" })

                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">

                                                @Html.LabelFor(m => m.Role, htmlAttributes: new { @class = "control-label" })


                                                @Html.DropDownListFor(m => m.Role, new List<SelectListItem> { new SelectListItem { Text = "Select Role", Value = " " }, new SelectListItem { Text = "Team Lead", Value = "Team Lead" }, new SelectListItem { Text = "Sr. Member", Value = "Sr. Member" }, new SelectListItem { Text = "Member", Value = "Member" } }, htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.Role, "", new { @class = "text-danger" })

                                            </div>
                                        </div>
                                        <div class="col-md-3">

                                            <button type="submit" style="margin-top: 25px;" id="BtnRegistrationSubmit" class="btn btn-dropbox text-center"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </div>
                                   
                                    <div class="row">
                                        <div class="col-md-12">
                                            <table id="example1" class="table table-bordered table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Sr #</th>
                                                        <th>Team Name</th>
                                                        <th>Employee Name</th>
                                                        <th>Email</th>
                                                        <th>Action</th>

                                                    </tr>
                                                </thead>
                                                <tbody id="Team_Members">
                                                    <tr>
                                                        <td>1</td>
                                                        <td>Team A</td>
                                                        <td>Amad Durrani</td>
                                                        <td>amadatiq786@gmail.com</td>
                                                        <td><button class="btn btn-danger"><i class="fa fa-times"></i></button></td>
                                                    </tr>
                                                </tbody>

                                            </table>
                                        </div>

                                    </div>

                                </div><!-- /.box-body -->
                                <div class="box-footer" style="text-align: center;">
                                    <button class="btn btn-primary">Proceed to teams</button>
                                </div><!-- /.box-footer-->
                            </div>
                        </fieldset>

                    }

                </div>
            </div>

            <div class="col-md-1"></div>
        </div>
    </div>

    <!-- end widget content -->

</section><!-- /.content -->
<section class="content"></section>

SDGSDB/Views/Project/AddProjectManager.cshtml
@model SDGSDB.Models.ProjectManagers

@{
    ViewBag.Title = "AddProjectManager";
    Layout = "~/Views/Layouts/_DashboardLayout.cshtml";
}
@Scripts.Render("~/Scripts/jquery-3.4.1.js")
@Scripts.Render("~/Scripts/jquery-3.4.1.min.js")
@Scripts.Render("~/Scripts/bootstrap.min.js")
<section class="content">


    <div class="row">

        <div class="col-md-12">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <div class="row">
                    @using (Html.BeginForm("AddProjectManager", "Project", FormMethod.Post, new { @class = "form", role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <fieldset>
                            <!-- Default box -->
                            <div class="box box-danger">
                                <div class="box-header with-border">
                                    <div class="well">
                                        <h3><img width="70" src="~/Images/sdgs_circle.png" /> Assign Project to Project Manager(s)</h3>
                                    </div>

                                </div>
                                <div class="box-body">
                                   
                                    @*@Html.ValidationSummary(true, null, new { @Class = "text-danger" })*@
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">

                                                @Html.LabelFor(m => m.ProjectId, htmlAttributes: new { @class = "control-label" })
                                                

                                                    @Html.DropDownListFor(m => m.ProjectId, new List<SelectListItem> { new SelectListItem { Text = "Select Project", Value = " " }, new SelectListItem { Text = "Proj 1", Value = "1" }, new SelectListItem { Text = "Proj 2", Value = "2" }, new SelectListItem { Text = "Proj 3", Value = "3" } }, htmlAttributes: new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(m => m.ProjectId, "", new { @class = "text-danger" })
                                                
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">

                                                @Html.LabelFor(m => m.EmployeeId, htmlAttributes: new { @class = "control-label" })
                                                
                                                    @Html.DropDownListFor(m => m.EmployeeId, new List<SelectListItem> { new SelectListItem { Text = "Select Employee", Value = " " }, new SelectListItem { Text = "Emp 1", Value = "1" }, new SelectListItem { Text = "Emp 2", Value = "2" }, new SelectListItem { Text = "Emp 3", Value = "3" } }, htmlAttributes: new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(m => m.EmployeeId, "", new { @class = "text-danger" })
                                                
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            
                                            <button type="submit" style="margin-top: 25px;" id="BtnRegistrationSubmit" class="btn btn-dropbox text-center"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </div>
                                <hr />
                                    <div class="row">
                                        <div class="col-md-12">
                                            <table id="example1" class="table table-bordered table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Sr #</th>
                                                        <th>Project Name</th>
                                                        <th>Employee Name</th>
                                                        <th>Email</th>
                                                        <th>Cointact #</th>
                                                        <th>Action</th>

                                                    </tr>
                                                </thead>
                                                <tbody id="ProjectManagers">
                                                   <tr>
                                                       <td>1</td>
                                                       <td>Project 1</td>
                                                       <td>Amad Durrani</td>
                                                       <td>amadatiq786@gmail.com</td>
                                                       <td>92123456789</td>
                                                       <td><button class="btn btn-danger"><i class="fa fa-times"></i></button></td>
                                                   </tr>
                                                </tbody>

                                            </table>
                                        </div>
                                        
                                    </div>

                                </div><!-- /.box-body -->
                                <div class="box-footer" style="text-align: center;">
                                    <button class="btn btn-primary">Proceed to teams</button>
                                </div><!-- /.box-footer-->
                            </div>
                        </fieldset>

                    }

                </div>
            </div>
            
            <div class="col-md-1"></div>
        </div>
    </div>

    <!-- end widget content -->

</section><!-- /.content -->
<section class="content"></section>

@Scripts.Render("~/bundles/jqueryval")

SDGSDB/Views/Project/AddTeams.cshtml
@model SDGSDB.Models.ProjectTeams
@{
    ViewBag.Title = "AddTeams";
    Layout = "~/Views/Layouts/_DashboardLayout.cshtml";
}
@Scripts.Render("~/Scripts/jquery-3.4.1.js")
@Scripts.Render("~/Scripts/jquery-3.4.1.min.js")
@Scripts.Render("~/Scripts/bootstrap.min.js")
<section class="content">


    <div class="row">

        <div class="col-md-12">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <div class="row">
                    @using (Html.BeginForm("AddTeams", "Project", FormMethod.Post, new { @class = "form", role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <fieldset>
                            <!-- Default box -->
                            <div class="box box-danger">
                                <div class="box-header with-border">
                                    <div class="well">
                                        <h3><img width="70" src="~/Images/sdgs_circle.png" /> Create Teams for project</h3>
                                    </div>

                                </div>
                                <div class="box-body">
                                    <legend>Select Teams</legend>
                                    @*@Html.ValidationSummary(true, null, new { @Class = "text-danger" })*@
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">

                                                @Html.LabelFor(m => m.ProjectId, htmlAttributes: new { @class = "control-label" })
                                                

                                                    @Html.DropDownListFor(m => m.ProjectId, new List<SelectListItem> { new SelectListItem { Text = "Select Project", Value = " " }, new SelectListItem { Text = "Proj 1", Value = "1" }, new SelectListItem { Text = "Proj 2", Value = "2" }, new SelectListItem { Text = "Proj 3", Value = "3" } }, htmlAttributes: new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(m => m.ProjectId, "", new { @class = "text-danger" })
                                                
                                            </div>
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">

                                                @Html.LabelFor(m => m.TeamName, htmlAttributes: new { @class = "control-label" })
                                                
                                                    @Html.EditorFor(m => m.TeamName, new { htmlattributes = new { @class = "form-control", id = "txtteamname", placeholder = "Team Name" } })
                                                    @Html.ValidationMessageFor(m => m.TeamName, "", new { @class = "text-danger" })
                                                

                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">

                                                @Html.LabelFor(m => m.Description, htmlAttributes: new { @class = "control-label" })
                                                <div class="input-group">
                                                    @Html.TextAreaFor(m => m.Description, 7, 175, new { htmlattributes = new { @class = "form-control", id = "txtteamname", placeholder = "Team Name" } })
                                                    @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div><!-- /.box-body -->
                                <div class="box-footer" style="text-align: center;">
                                    <button class="btn btn-primary">Create team</button>
                                </div><!-- /.box-footer-->
                            </div>
                        </fieldset>

                    }

                </div>
            </div>

            <div class="col-md-1"></div>
        </div>
    </div>

    <!-- end widget content -->

</section><!-- /.content -->
<section class="content"></section>

@Scripts.Render("~/bundles/jqueryval")