SDGSDB/Models/UCProfile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SDGSDB.Models
{
    public class UCProfile
    {
        public int UC_Id { get; set; }
        public string UC_Name { get; set; }
        public string Province_Name { get; set; }
        public string Division_Name { get; set; }
        public string District_Name { get; set; }
        public string Tehsil_Name { get; set; }
        public string Area { get; set; }
        public string Population { get; set; }
        public string MalePopulation { get; set; }
        public string FemalePopulation { get; set; }
        public string OtherLocality { get; set; }
        public string Climate { get; set; }
        public string RoadInfrastructure { get; set; }
        public string Organization_Type_Id { get; set; }
        public string Name { get; set; }
        public string Person_Contat_Number { get; set; }
        public string Person_Contat_Email { get; set; }

    }
}

SDGSDB/Models/ViewModels/TourismSpotViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SDGSDB.Models.ViewModels
{   
        public class TourismSpotViewModel
        {
            public UCTourismSpotModel TourismSpotModel { get; set; }
            public UCTourismSpotGallaryModel TourismSpotGallaryModel { get; set; }
        }
        public class UCTourismSpotModel
        {
            public int TouristSpotId { get; set; }
            [Required]
            [Display(Name = "Tourist Spot Name")]
            public string TouristSpotName { get; set; }
            [Required]
            [Display(Name = "Tourist Spot Category")]
            public int TouristSpotCategory { get; set; }
            [Required]
            [Display(Name = "Popularity")]
            public string Popularity { get; set; }
            [Required]
            [Display(Name = "Address")]
            public string Address { get; set; }
            [Required]
            [Display(Name = "Hotel")]
            public string IsHotel { get; set; }
            [Required]
            [Display(Name = "Restaurant")]
            public string IsRestaurant { get; set; }
            [Required]
            [Display(Name = "Accommodation)")]
            public string IsAccommodation { get; set; }
            [Required]
            [EmailAddress]
            [Display(Name = "Shop")]
            public string IsShop { get; set; }
            [Required]
            [Display(Name = "Time Open")]
            public string TimeOpen { get; set; }
            [Required]
            [Display(Name = "Time Close")]
            public string TimeClose { get; set; }
            [Required]
            [Display(Name = "Description")]
            public string Description { get; set; }

        }

        public class UCTourismSpotGallaryModel
        {
            public int TourismSpotGallaryId { get; set; }
            [Required]
            [Display(Name = "Tourist Spot ID")]
            public int ToursimSpotId { get; set; }
            [Required]
            [Display(Name = "Tourist Spot Image")]
            public string SpotImage { get; set; }
        }
    
}

SDGSDB/Controllers/UnionCouncilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using SDGSDB.Models;

namespace SDGSDB.Controllers
{
    public class UnionCouncilController : Controller
    {
        //New Union Council
        [Authorize(Roles = "APP_USER,UC_ADMIN")]
        public ActionResult UnionCouncil(int UCID)
        {
            var GUID = HttpContext.User.Identity.GetUserId();
            ViewBag.CurrentUserID = GUID;
            ViewBag.UCID = UCID;
            return View();
        }
        [Authorize(Roles = "APP_USER,UC_ADMIN")]
        public ActionResult UnionCouncilOrg()
        {
            var GUID = HttpContext.User.Identity.GetUserId();
            ViewBag.CurrentUserID = GUID;
            string ApiBaseUrl = System.Web.Configuration.WebConfigurationManager.AppSettings["ApiBaseUrl"];
            try
            {
                var result = "";
                HttpClient client = new HttpClient();
                var response = client.GetAsync(ApiBaseUrl + "/GetAllUCInstitutionByUC?UserID=" + GUID).Result;
                if (response.IsSuccessStatusCode)
                {
                    result = response.Content.ReadAsStringAsync().Result;
                }
                UCOrgInstitutionsModel[] items = JsonConvert.DeserializeObject<UCOrgInstitutionsModel[]>(result);
                ViewBag.AllUCInstitution = items;
            }
            catch (Exception ex)
            {
                var message = ex.Message;
                throw;
            }
            return View();
        }
        [Authorize(Roles = "APP_USER,UC_ADMIN")]
        public ActionResult UnionCouncilOrgInstitutions(int Sector_Category_Id)
        {
            var GUID = HttpContext.User.Identity.GetUserId();
            ViewBag.CurrentUserID = GUID;
            string ApiBaseUrl = System.Web.Configuration.WebConfigurationManager.AppSettings["ApiBaseUrl"];
            try
            {
                var result = "";
                HttpClient client = new HttpClient();
                var response = client.GetAsync(ApiBaseUrl + "/GetAllUCInstitutionByUCSectorsCat?UserID=" + GUID+ "&Sector_Category_Id="+ Sector_Category_Id).Result;
                if (response.IsSuccessStatusCode)
                {
                    result = response.Content.ReadAsStringAsync().Result;
                }
                UCOrgInstitutionsModel[] items = JsonConvert.DeserializeObject<UCOrgInstitutionsModel[]>(result);
                ViewBag.AllUCInstitutionsBySectors = items;
            }
            catch (Exception ex)
            {
                var message = ex.Message;
                throw;
            }
            return View();
        }
        [Authorize(Roles = "APP_USER,UC_ADMIN")]
        public ActionResult UCRegistration()
        {
            var GUID = HttpContext.User.Identity.GetUserId();
            ViewBag.CurrentUserID = GUID;
            return View();
        }
        [Authorize(Roles = "APP_USER,UC_ADMIN")]
        public ActionResult UCProfileView()
        {
            var GUID = HttpContext.User.Identity.GetUserId();
            ViewBag.CurrentUserID = GUID;
            return View();
        }
        [Authorize(Roles = "APP_USER,UC_ADMIN")]
        public ActionResult UCStaff()
        {
            var GUID = HttpContext.User.Identity.GetUserId();
            ViewBag.CurrentUserID = GUID;
            return View();
        }
        [Authorize(Roles = "APP_USER,UC_ADMIN")]
        public ActionResult TourismSpot()
        {
            var GUID = HttpContext.User.Identity.GetUserId();
            ViewBag.CurrentUserID = GUID;
            return View();
        }
    }

}

SDGSDB/Views/UnionCouncil/UnionCouncilOrgInstitutions.cshtml
@{
    ViewBag.Title = "UnionCouncilOrgInstitutions";
    Layout = "~/Views/Layouts/_DashboardLayout.cshtml";
}


@Scripts.Render("~/Scripts/jquery-3.4.1.js")
@Scripts.Render("~/Scripts/jquery-3.4.1.min.js")
<section class="content">
    <div class="row" id="UCOrg_form">
        <!-- left column -->
        <div class="col-md-12">
            <!-- form start -->
            @using (Html.BeginForm("UnionCouncilOrg", "UnionCouncil", FormMethod.Post, new { @class = "form", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <fieldset>
                    <div class="box box-success">
                        <div class="box-header with-border">
                            <div class="col-sm-1"></div>
                            <div class="col-sm-10" style="padding: 0px;">
                                <div class="well" style="padding:10px;border-radius:20px;">
                                    <h3><img width="50" src="~/Images/sdgs_circle.png" />Union Council Organization And Institutions Detail:</h3>
                                </div>
                            </div>
                            <div class="col-sm-1"></div>
                        </div><!-- /.box-header -->
                        <div class="box-body">

                            <div class="row">
                                <div class="col-sm-1"></div>
                                <div class="col-md-10">
                                    <!-- Primary box -->
                                    <div class="box box-solid box-primary">
                                        <div class="box-header">
                                            <h3 class="box-title">Sector's Institutions Detail:</h3>
                                            <div class="box-tools pull-right">
                                                <button class="btn btn-primary btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>

                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <div class="box">
                                                        <div class="box-header">
                                                            <h3 class="box-title">Institution's Detail:</h3>
                                                            <div class="box-tools">
                                                            </div>
                                                        </div><!-- /.box-header -->
                                                        <div class="box-body">
                                                            <table id="example1" class="table table-bordered table-striped">
                                                                <thead>
                                                                    <tr>
                                                                        <th>S.No</th>
                                                                        <th>Sector</th>
                                                                        <th>Sector Category</th>
                                                                        <th>Institution Name</th>
                                                                        <th>Nature</th>
                                                                        <th>Contact</th>
                                                                        <th>Email</th>
                                                                        <th>Action</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody id="TableL">
                                                                    @if (ViewBag.AllUCInstitutionsBySectors != null)
                                                                    {
                                                                        int id = 1;
                                                                        foreach (var item in ViewBag.AllUCInstitutionsBySectors)
                                                                        {
                                                                            <tr id="row_@item.UC_OrganizationId">
                                                                                <td>@id</td>
                                                                                <td>@item.Sector_Name</td>
                                                                                <td>@item.Category_Name</td>
                                                                                <td>@item.Organization</td>
                                                                                <td>@item.OrganizationNature</td>
                                                                                <td>@item.ContactNumber</td>
                                                                                <td>@item.EmailAddress</td>
                                                                                <td>
                                                                                    <button value="@item.UC_OrganizationId" id="btn_OrgUCDelete" title="Delete" class="btn btn-danger"> Delete <i class="fa fa-trash-o"></i></button>
                                                                                    <button value="@item.UC_OrganizationId" id="btn_OrgUCEdit" title="Edit" class="btn btn-primary"> Edit <i class="fa fa-eye-slash"></i></button>
                                                                                </td>

                                                                            </tr>
                                                                            id++;
                                                                        }
                                                                    }
                                                                </tbody>
                                                            </table>

                                                        </div><!-- /.box-body -->
                                                    </div><!-- /.box -->
                                                </div>
                                            </div>
                                        </div><!-- /.box-body -->
                                        <div class="box-footer">

                                        </div>
                                    </div><!-- /.box -->
                                </div>
                                <div class="col-sm-1"></div>
                            </div>

                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer" style="text-align:center">
                            @*<button type="submit" style="border-radius:10px;text-align: center;" id="btnEmployeeSubmit" class="btn btn-primary"><i class="glyphicon glyphicon-save"></i> Submit</button>*@
                            @*<a href="/Organization/EmployeesDetail" style="margin-left:10px" class="btn btn-success"><i class="glyphicon glyphicon-th-large"></i> Detail</a>*@
                        </div>

                    </div><!-- /.box -->
                </fieldset>
            }
        </div><!--/.col (left) -->
        <!-- right column -->
    </div>   <!-- /.row -->
</section>

@Scripts.Render("~/bundles/jqueryval")